apiVersion: v1
kind: Service
metadata:
  name: lorcana-web
  namespace: lorcana
  labels:
    app: lorcana-web
spec:
  type: NodePort
  selector:
    app: lorcana-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30710
